server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Customer Service - Ruta base
        - id: customer-service-base
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers
          filters:
            - SetPath=/api/v1/customers
        
        # Customer Service - Con parámetros
        - id: customer-service-params
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<remaining>.*), /api/v1/customers/${remaining}
        
        # Account Service - Ruta base
        - id: account-service-base
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts
          filters:
            - SetPath=/api/v1/accounts
        
        # Account Service - Con parámetros
        - id: account-service-params
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<remaining>.*), /api/v1/accounts/${remaining}
        
        # Auth Service - Ruta base
        - id: auth-service-base
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth
          filters:
            - SetPath=/api/v1/auth
        
        # Auth Service - Con parámetros
        - id: auth-service-params
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<remaining>.*), /api/v1/auth/${remaining}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

resilience4j:
  circuitbreaker:
    instances:
      customerServiceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      accountServiceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      authServiceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
