server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # AUTH-SERVICE (rutas públicas)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
        
        # CUSTOMER-SERVICE
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
        
        # ACCOUNT-SERVICE
        - id: account-service-accounts
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
        
        - id: account-service-transactions
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:5}  # ← AQUÍ cambias la duración


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.bank.gateway: DEBUG
