server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Customer Service
- id: customer-service
  uri: lb://customer-service
  predicates:
    - Path=/api/customers, /api/customers/**
  filters:
    - RewritePath=/api/customers/?(?<segment>.*), /api/v1/customers/${segment}

# Account Service
- id: account-service
  uri: lb://account-service
  predicates:
    - Path=/api/accounts, /api/accounts/**
  filters:
    - RewritePath=/api/accounts/?(?<segment>.*), /api/v1/accounts/${segment}

# Auth Service
- id: auth-service
  uri: lb://auth-service
  predicates:
    - Path=/api/auth, /api/auth/**
  filters:
    - RewritePath=/api/auth/?(?<segment>.*), /api/v1/auth/${segment}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    com.bank.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
