server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false

# Configuraci贸n JWT
jwt:
  secret: miClaveSecretaSuperSeguraParaJWT2024NTTDataBootcamp
  expiration: 86400000  # 24 horas en milisegundos

# Configuraci贸n de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Configuraci贸n de Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      customerServiceCircuitBreaker:
        baseConfig: default
      accountServiceCircuitBreaker:
        baseConfig: default
      creditServiceCircuitBreaker:
        baseConfig: default
      transactionServiceCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      authServiceRetry:
        baseConfig: default
      customerServiceRetry:
        baseConfig: default
      accountServiceRetry:
        baseConfig: default
      creditServiceRetry:
        baseConfig: default
      transactionServiceRetry:
        baseConfig: default

# Configuraci贸n de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    com.bank.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
