server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # AUTH-SERVICE 🔐
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
        
        # CUSTOMER-SERVICE
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
        
        # ACCOUNT-SERVICE (accounts)
        - id: account-service-accounts
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            # SIN PrefixPath - porque el servicio no tiene /api/v1
        
        # ACCOUNT-SERVICE (transactions)
        - id: account-service-transactions
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
            # SIN PrefixPath - porque el servicio no tiene /api/v1
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012}
  expiration-ms: ${JWT_EXPIRATION:200000} 
