server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # AUTH-SERVICE 🔐
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/v1/auth/${segment}
        
        # CUSTOMER-SERVICE
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /api/v1/customers/${segment}
        
        # ACCOUNT-SERVICE (accounts)
        - id: account-service-accounts
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<segment>.*), /api/v1/accounts/${segment}
        
        # ACCOUNT-SERVICE (transactions)
        - id: account-service-transactions
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions/(?<segment>.*), /api/v1/transactions/${segment}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012}
  expiration-ms: ${JWT_EXPIRATION:1800000}  # 30 minutos
