server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Customer Service - Base
        - id: customer-service-base
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers
          filters:
            - SetPath=/api/v1/customers
        
        # Customer Service - With params
        - id: customer-service-params
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<remaining>.*), /api/v1/customers/${remaining}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# CONFIGURACIÓN CRÍTICA DEL ACTUATOR
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"  # ← Usa comillas dobles y asterisco
      base-path: /actuator

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
