server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Customer Service
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE  # ← MAYÚSCULAS como aparece en Eureka
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers(?<segment>.*), /api/v1/customers${segment}
        
        # Account Service
        - id: account-service
          uri: lb://ACCOUNT-SERVICE  # ← MAYÚSCULAS
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts(?<segment>.*), /api/v1/accounts${segment}
        
        # Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE  # ← MAYÚSCULAS
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>.*), /api/v1/auth${segment}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ← Cambia a * para exponer todos
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.bank.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
