server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>.*), /api/v1/auth${segment}
        
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers(?<segment>.*), /api/v1/customers${segment}
        
        - id: account-service-accounts
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts(?<segment>.*), /api/v1/accounts${segment}
        
        - id: account-service-transactions
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions(?<segment>.*), /api/v1/transactions${segment}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
jwt:
  secret: "un_secreto_de_32_o_mas_caracteres___________OK"
  expiration-minutes: 1440  # ✅ CAMBIO: 24 horas (antes eran 86400000 ms)
