server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Customer Service
        - id: customer-service-base
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers
          filters:
            - SetPath=/api/v1/customers
        
        - id: customer-service-params
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<remaining>.*), /api/v1/customers/${remaining}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    gateway:
      enabled: true  # ← MUY IMPORTANTE
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: gateway,health,info  # ← Especifica gateway explícitamente

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
