server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # usamos nuestro decoder custom, pero esto evita conflictos
          jws-algorithms: HS256

  cloud:
    gateway:
      routes:

        # AUTH-SERVICE 🔐
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>.*), /api/v1/auth${segment}

        # CUSTOMER
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers(?<segment>.*), /api/v1/customers${segment}

        # ACCOUNTS (account-service)
        - id: account-service-accounts
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts(?<segment>.*), /api/v1/accounts${segment}

        # TRANSACTIONS (account-service)
        - id: account-service-transactions
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions(?<segment>.*), /api/v1/transactions${segment}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

# 👇 ESTA ES LA PROPIEDAD QUE NECESITA SecurityConfig
jwt:
  secret: mySecretKey1234567890123456789012
