server:
  port: 8082

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: account_db
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8085/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: account-service