server:
  port: 8083

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: mySuperSecretKey1234567890  # la misma que usarás en el gateway
  expiration-minutes: 30              # tiempo de vida del token

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
