server:
  port: 8082

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account_db
      auto-index-creation: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10

# WebClient Configuration for customer-service
customer-service:
  url: http://customer-service  # Eureka will resolve this

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,openapi
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true  

info:
  app:
    name: Account Service
    description: Microservicio de gestión de cuentas bancarias (ahorros, corriente, plazo fijo)
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
  team:
    name: Banking System Team
    project: NTTData Final Project
  build:
    artifact: account-service
    group: com.bank

# OpenAPI/Swagger Documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Logging
logging:
  level:
    root: INFO
    com.bank.account: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
