server:
  port: 8082

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account_db
      auto-index-creation: true

# WebClient (Eureka resolverá el nombre)
customer-service:
  url: http://customer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.bank.account: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
