server:
  port: 8081

spring:
  application:
    name: customer-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer_db
      auto-index-creation: true
  
  # Configuración de Redis (AGREGAR ESTO)
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  
  # Configuración de caché (AGREGAR ESTO)
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutos en milisegundos
      cache-null-values: false

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: always
    info:
      env:
        enabled: true

# Application Info
info:
  app:
    name: Customer Service
    description: Microservicio de gestión de clientes (personal y empresarial)
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
  team:
    name: Banking System Team
    project: NTTData Final Project
  build:
    artifact: customer-service
    group: com.bank

# OpenAPI/Swagger Documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Logging
logging:
  level:
    root: INFO
    com.bank.customer: DEBUG
    org.springframework.data.mongodb: DEBUG
