server:
  port: 8082

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account_db
      auto-index-creation: true

customer-service:
  url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
